### ISSUE TITLE
terminology for activity mitigators needs to match NEE exercise

### ISSUE THREAD

**Issue by yiwen-h** [The-Strategy-Unit/nhp_inputs#186]

**Comment by matt-dray** [comment]
To note: the majority of YAML keys do not match between the config files of nhp_inputs and nhp_elicitation_tool. This is due to hyphen/underscore mismatches, typos, wording differences and existence of two keys instead of one (EOL care, specifically). I've focused on updating only the values (i.e. strategy subset names) and have not altered any keys.
